# Generated by Django 4.2.25 on 2025-11-13 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('grammar', 'Gramática'), ('theme', 'Temática')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('netflix', 'Netflix'), ('web', 'Web'), ('pdf', 'PDF')], max_length=50, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='phrases', to='phrases.category')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_phrases', to='phrases.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_phrases', to='phrases.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phrases',
                'ordering': ['-created_at'],
            },
        ),
    ]
