# Generated by Django 4.2.25 on 2025-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
