# Generated by Django 4.2.25 on 2025-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardreview',
            name='interval_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='mode_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
