# Generated by Django 4.2.25 on 2025-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcardreview_interval_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardreview',
            old_name='interval_days',
            new_name='interval',
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='ef',
            field=models.FloatField(default=2.5),
        ),
    ]
