# Generated by Django 4.2.25 on 2025-11-13 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('streak_7', '7 días consecutivos'), ('streak_30', '30 días consecutivos'), ('streak_100', '100 días consecutivos'), ('phrases_50', '50 frases guardadas'), ('phrases_100', '100 frases guardadas'), ('phrases_500', '500 frases guardadas'), ('perfect_10', '10 sesiones perfectas'), ('speed_demon', 'Contrarreloj < 2 min'), ('polyglot', '3+ idiomas'), ('points_1000', '1,000 puntos'), ('points_5000', '5,000 puntos'), ('points_10000', '10,000 puntos')], max_length=50)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'unique_together': {('user', 'achievement_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phrases_practiced', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('practice_minutes', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('streak_maintained', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_statistics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
