# Generated by Django 4.2.25 on 2025-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_userstreak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStreak',
        ),
    ]
